### ISSUE TITLE
Missing RestSharp dependency

### ISSUE THREAD

**Issue by c-w** [pseudomuto/githubpushlib#1]
Hi @pseudomuto,

First of all: thanks for creating this easy-to-use library.

One minor concern: the package available via NuGet seems to be missing a dependency on RestSharp. A basic use-case using `ContentService`, `FileTarget` and `DiskFile` leads to the following exception:

<img src="https://cloud.githubusercontent.com/assets/1086421/12876104/781d195c-cdae-11e5-856e-1dda7347394e.png" width=400/>

Adding a dependency on RestSharp fixes the problem. Sample `packages.config` file:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="RestSharp" version="105.2.3" targetFramework="net452" />
</packages>
```

**Comment by pseudomuto** [comment]
Hey, thanks for looking into this! Any interest in making a PR?
